name: born2bewild
description: "Your application with Privy web integration"

# Version of your application
version: 1.0.0+1

ios:
  bundle_identifier: com.example.born2bewild

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.2.5
  uni_links: ^0.5.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add here your assets, fonts, etc.
  assets:
    - .env
    - assets/