name: born2bewild
description: "Your application with Privy web integration"

# Version of your application
version: 1.0.0+1

ios:
  bundle_identifier: com.example.born2bewild

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  uni_links: ^0.5.1
  provider: ^6.0.5
  camera: ^0.10.5
  mobile_scanner: ^3.5.6
  image_picker: ^1.0.7
  http: ^1.1.0
  walletconnect_dart: ^0.0.11
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  permission_handler: ^10.2.0
  solana_wallet_adapter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add here your assets, fonts, etc.
  assets:
    - .env
    - assets/
    - assets/logo.png
    - assets/images/
    - assets/icons/
    - assets/images/tigre.jpg
    - assets/images/gorilla.jpg